if the output of summary is empty API tests did not run

diff --git a/sources/main.yml b/sources/main.yml
--- a/sources/main.yml
+++ b/sources/main.yml
@@ -33,9 +33,23 @@ jobs:
         reporters: cli
         bail: true
 
-    - name: Output summary to console
-      run: echo ${{ steps.run-newman.outputs.summary }}
+    - name: Check if we failed
+      id: fail-check
+      shell: bash
+      env:
+        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
+      run: |
+        printf '%s\n' "$JSON_DOC" > summary.json
+        cat summary.json
+        if grep -q Collection summary.json; then
+          echo "failed=false" >> $GITHUB_OUTPUT;
+        else
+          echo "failed=true" >> $GITHUB_OUTPUT;
+        fi
 
+    - name: fail if empty
+      if: ${{ steps.fail-check.outputs.failed == 'true' }}
+      run: exit 1
 
     - name: Login to Container Registry
       uses: docker/login-action@v1
